# Generated by Django 5.0.6 on 2024-05-15 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=200)),
                ("gender", models.CharField(max_length=200)),
                ("ghin_status", models.CharField(max_length=200)),
                ("ghin_number", models.CharField(max_length=200)),
                ("tshirt_size", models.CharField(max_length=200)),
                ("meal_preference", models.CharField(max_length=200)),
                ("cart_sitting_preference", models.CharField(max_length=200)),
                ("player_level", models.CharField(max_length=200)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="falconcup.team"
                    ),
                ),
            ],
        ),
    ]
