# Generated by Django 5.0.6 on 2024-05-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("falconcup", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="email",
            field=models.EmailField(max_length=200),
        ),
    ]
