# Generated by Django 5.0.6 on 2024-05-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("falconcup", "0002_alter_teammember_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="player_level",
            field=models.CharField(
                choices=[("TM", "Team Member"), ("CP", "Captain")],
                default="TM",
                max_length=2,
            ),
        ),
    ]
