# Generated by Django 5.0.6 on 2024-05-17 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("falconcup", "0003_alter_teammember_player_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="cart_sitting_preference",
            field=models.CharField(
                choices=[("WALK", "Walk"), ("CART", "Cart")], max_length=4
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")], max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="ghin_status",
            field=models.CharField(
                choices=[
                    ("ACT", "Active"),
                    ("INA", "Inactive"),
                    ("DHO", "Don't have one"),
                ],
                default="ACT",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="meal_preference",
            field=models.CharField(
                choices=[("MEAT", "Meat"), ("VEG", "Vegetarian")], max_length=4
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="falconcup.team",
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="tshirt_size",
            field=models.CharField(
                choices=[
                    ("XS", "XS"),
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("XL", "XL"),
                    ("XXL", "XXL"),
                ],
                max_length=3,
            ),
        ),
    ]
