# Generated by Django 5.0.6 on 2024-06-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("falconcup", "0004_team_url_code_alter_teammember_team_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="corporate_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="ghin_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ACT", "Active"),
                    ("INA", "Inactive"),
                    ("DHO", "Don't have one"),
                ],
                default="ACT",
                max_length=3,
                null=True,
                verbose_name="GHIN Status",
            ),
        ),
    ]
