# Generated by Django 5.0.6 on 2024-06-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("falconcup", "0005_teammember_corporate_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="terms_accepted",
            field=models.BooleanField(default=True, verbose_name="Has Accepted Terms"),
        ),
    ]
