# Generated by Django 5.0.6 on 2024-06-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("falconcup", "0006_teammember_terms_accepted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="terms_accepted",
            field=models.BooleanField(default=False, verbose_name="Has Accepted Terms"),
        ),
    ]
