# Generated by Django 5.0.6 on 2024-06-13 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("falconcup", "0007_alter_teammember_terms_accepted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="terms_accepted",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Has Accepted Terms"
            ),
        ),
    ]
