# Generated by Django 5.0.6 on 2024-06-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("falconcup", "0008_alter_teammember_terms_accepted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="cart_sitting_preference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "— Please choose an option —"),
                    ("WALK", "Walk"),
                    ("CART", "Cart"),
                ],
                max_length=4,
                verbose_name="Cart Sitting Preference",
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "— Please choose an option —"),
                    ("M", "Male"),
                    ("F", "Female"),
                    ("O", "Other"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="ghin_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "— Please choose an option —"),
                    ("ACT", "Active"),
                    ("INA", "Inactive"),
                    ("DHO", "Don't have one"),
                ],
                default="ACT",
                max_length=3,
                null=True,
                verbose_name="GHIN Status",
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="meal_preference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "— Please choose an option —"),
                    ("MEAT", "Meat"),
                    ("VEG", "Vegetarian"),
                ],
                max_length=4,
                verbose_name="Meal Preference",
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="tshirt_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "— Please choose an option —"),
                    ("XS", "XS"),
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("XL", "XL"),
                    ("XXL", "XXL"),
                ],
                max_length=3,
                verbose_name="T-Shirt Size",
            ),
        ),
    ]
