# Generated by Django 5.0.6 on 2024-06-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("falconcup", "0009_alter_teammember_cart_sitting_preference_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="gender",
            field=models.CharField(
                choices=[
                    ("", "— Please choose an option —"),
                    ("M", "Male"),
                    ("F", "Female"),
                    ("O", "Other"),
                ],
                max_length=200,
            ),
        ),
    ]
